# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: gcc:5.4
image: xinzhang8noaa/jedibox_dockerfile:latest

pipelines:
  custom:
    default:
      - step:
          script: # Modify the commands below to build your repository.
            # Print the number of processing cores
            - nproc
            # Print the Linux version.
            - uname -a
            # Print the version.
            - gcc --version
            - gfortran --version
            - cmake --version          
            - mkdir build
            - cd build
            # Call the CMake.
            - cmake ..
            # Build the porject.
            - make -j`nproc`
