# syntax=docker/dockerfile:experimental
FROM  jcsda/docker_base-intel-oneapi-dev:beta
LABEL maintainer "Mark Miesch <miesch@ucar.edu>"

SHELL ["/bin/bash", "-c"]

RUN rm -f /usr/bin/gmake && \
    ln -s /usr/bin/make /usr/bin/gmake

ARG DEBIAN_FRONTEND=noninteractive
ARG APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends -o=Dpkg::Use-Pty=0 \
        build-essential \
        ca-certificates \
        curl \
        git \
        gnupg \
        libexpat1-dev \
        libssl-dev \
        m4 \
        pkg-config \
        python \
        vim \
        wget \
        --

ENV I_MPI_THREAD_SPLIT=1 \
    I_MPI_LIBRARY_KIND='release_mt'

# set environment variables manually
ENV CMAKE_C_COMPILER=mpiicc \
    CMAKE_CXX_COMPILER=mpiicpc \
    CMAKE_Fortran_COMPILER=mpiifort \
    CMAKE_Platform=linux.intel \
    CMAKE_PREFIX_PATH=/usr/local \
    NETCDF=/usr/local \
    CC=mpiicc \
    CXX=mpiicpc \
    FC=mpiifort \
    MPI_CC=mpiicc \
    MPI_CXX=mpiicpc \
    MPI_FC=mpiifort \
    SERIAL_CC=icc \
    SERIAL_CXX=icpc \
    SERIAL_FC=ifort \
    PNETCDF=/usr/local \
    HDF5_ROOT=/usr/local \
    PIO=/usr/local \
    BOOST_ROOT=/usr/local \
    EIGEN3_INCLUDE_DIR=/usr/local \
    SERIAL_CC=clang \
    SERIAL_CXX=clang++ \
    SERIAL_FC=gfortran \
    PATH=/usr/local/bin:$PATH \
    LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH \
    LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH \
    CPATH=/usr/local/include:$CPATH \
    PYTHONPATH=/usr/local/lib:$PYTHONPATH

# Download public key for github.com
RUN mkdir -p -m 0600 ~/.ssh && \
    ssh-keyscan github.com >> ~/.ssh/known_hosts

# set up ssh authentication
RUN git config --global url.ssh://git@github.com/.insteadOf https://github.com/

# build the jedi stack
RUN --mount=type=ssh,id=github_ssh_key cd /root \
    && source /etc/profile \
    && git clone git@github.com:jcsda-internal/jedi-stack.git \
    && cd jedi-stack/buildscripts \
    && git checkout feature/intel-oneapi \
    && ./build_stack.sh "container-intel-oneapi-dev" \
    && mv ../jedi-stack-contents.log /etc \
    && chmod a+r /etc/jedi-stack-contents.log \
    && rm -rf /root/jedi-stack \
    && mkdir /worktmp

#Make a non-root user:jedi / group:jedi for running MPI
RUN useradd -U -k /etc/skel -s /bin/bash -d /home/jedi -m jedi && \
    echo "export FC=mpiifort" >> ~jedi/.bashrc && \
    echo "export CC=mpiicc" >> ~jedi/.bashrc && \
    echo "export CXX=mpiicpc" >> ~jedi/.bashrc && \
    echo "export PYTHONPATH=/usr/local/lib:$PYTHONPATH" >> ~jedi/.bashrc && \
    echo "ulimit -s unlimited" >> ~jedi/.bashrc && \
    echo "ulimit -v unlimited" >> ~jedi/.bashrc && \
    echo -e "[credential]\n    helper = cache --timeout=7200" >> ~jedi/.gitconfig && \
    mkdir ~jedi/.openmpi && \
    echo "rmaps_base_oversubscribe = 1" >> ~jedi/.openmpi/mca-params.conf && \
    chown -R jedi:jedi ~jedi/.gitconfig ~jedi/.openmpi

CMD ["/bin/bash" , "-l"]
