FROM  jcsda/docker_base-gnu-openmpi-dev:latest
LABEL maintainer "Mark Miesch <miesch@ucar.edu>"

# set environment variables manually
ENV NETCDF=/usr/local \
   PNETCDF=/usr/local \
   HDF5_ROOT=/usr/local \
   PIO=/usr/local \
   BOOST_ROOT=/usr/local \
   EIGEN3_INCLUDE_DIR=/usr/local \
   LAPACK_PATH=/usr/local \
   LAPACK_DIR=$LAPACK_PATH \
   LAPACK_LIBRARIES="$LAPACK_PATH/lib/liblapack.a;$LAPACK_PATH/lib/libblas.a" \
   SERIAL_CC=gcc \
   SERIAL_CXX=g++ \
   SERIAL_FC=gfortran \
   MPI_CC=mpicc \
   MPI_CXX=mpicxx \
   MPI_FC=mpifort

# build the jedi stack
RUN cd /root \
    && git clone https://github.com/jcsda/jedi-stack.git \
    && cd jedi-stack/buildscripts \
    && git checkout develop \
    && ./build_stack.sh "container-gnu-openmpi-dev" \
    && mv ../jedi-stack-contents.log /etc \
    && chmod a+r /etc/jedi-stack-contents.log \
    && rm -rf /root/jedi-stack \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir /worktmp

#Setup the root users environment
ENV FC=mpifort \
   CC=mpicc \
   CXX=mpicxx

# install private repos
COPY ssh-key/github_academy_rsa /root/github_academy_rsa
RUN mkdir -p /root/.ssh && \
    mv /root/github_academy_rsa /root/.ssh/github_academy_rsa && \
    eval "$(ssh-agent -s)" && \
    ssh-add /root/.ssh/github_academy_rsa && \
    ssh -T -o "StrictHostKeyChecking=no" git@github.com; \
    mkdir -p /root/jedi && cd /root/jedi && \
    git clone git@github.com:jcsda/odc.git && \
    cd odc && git checkout develop && \
    mkdir -p build && cd build && \
    ecbuild --build=Release -DCMAKE_INSTALL_PREFIX="/usr/local" .. && \
    make -j4 && make install && \
    cd /root/jedi && \
    git clone git@github.com:jcsda/odyssey.git && \
    cd odyssey && git checkout develop && \
    mkdir -p build && cd build && \
    ecbuild --build=Release -DCMAKE_INSTALL_PREFIX="/usr/local" .. && \
    make -j4 && make install && \
    rm -rf /root/jedi/odc && \
    rm -rf /root/jedi/odyssey && \
    rm /root/.ssh/github_academy_rsa

#Make a non-root user:jedi / group:jedi for running MPI
RUN useradd -U -k /etc/skel -s /bin/bash -d /home/jedi -m jedi && \
    echo "export FC=mpifort" >> ~jedi/.bashrc && \
    echo "export CC=mpicc" >> ~jedi/.bashrc && \
    echo "export CXX=mpicxx" >> ~jedi/.bashrc && \
    echo "[credential]\n    helper = cache --timeout=7200" >> ~jedi/.gitconfig && \
    mkdir ~jedi/.openmpi && \
    echo "rmaps_base_oversubscribe = 1" >> ~jedi/.openmpi/mca-params.conf && \
    chown -R jedi:jedi ~jedi/.gitconfig ~jedi/.openmpi

# build lcov for Travis-CI
RUN cd /usr/local/src \
    && curl -L -O http://downloads.sourceforge.net/ltp/lcov-1.14.tar.gz \
    && tar -xvf lcov-1.14.tar.gz \
    && cd lcov-1.14 \
    && make install \
    && rm -rf /usr/local/src/*

CMD ["/bin/bash" , "-l"]
