# syntax=docker/dockerfile:experimental
FROM  jcsda/docker_base-gnu-openmpi-dev:beta
LABEL maintainer "Mark Miesch <miesch@ucar.edu>"

# set environment variables manually
ENV NETCDF=/usr/local \
   PNETCDF=/usr/local \
   HDF5_ROOT=/usr/local \
   PIO=/usr/local \
   BOOST_ROOT=/usr/local \
   EIGEN3_INCLUDE_DIR=/usr/local \
   LAPACK_PATH=/usr/local \
   LAPACK_DIR=$LAPACK_PATH \
   LAPACK_LIBRARIES="$LAPACK_PATH/lib/liblapack.a;$LAPACK_PATH/lib/libblas.a" \
   SERIAL_CC=gcc \
   SERIAL_CXX=g++ \
   SERIAL_FC=gfortran \
   MPI_CC=mpicc \
   MPI_CXX=mpicxx \
   MPI_FC=mpifort \
   PYTHONPATH=/usr/local/lib

SHELL ["/bin/bash", "-c"]

# Download public key for github.com
RUN mkdir -p -m 0600 ~/.ssh && \
    ssh-keyscan github.com >> ~/.ssh/known_hosts

# set up ssh authentication
RUN git config --global url.ssh://git@github.com/.insteadOf https://github.com/

# build the jedi stack
RUN --mount=type=ssh,id=github_ssh_key cd /root \
    && source /etc/profile \
    && git clone git@github.com:JCSDA-internal/jedi-stack.git \
    && cd jedi-stack/buildscripts \
    && git checkout develop \
    && ./build_stack.sh "container-gnu-openmpi-dev" \
    && mv ../jedi-stack-contents.log /etc \
    && chmod a+r /etc/jedi-stack-contents.log \
    && rm -rf /root/jedi-stack \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir /worktmp

#Setup the root users environment
ENV FC=mpifort \
   CC=mpicc \
   CXX=mpicxx

#Make a non-root user:jedi / group:jedi for running MPI
RUN useradd -U -k /etc/skel -s /bin/bash -d /home/jedi -m jedi && \
    echo "export FC=mpifort" >> ~jedi/.bashrc && \
    echo "export CC=mpicc" >> ~jedi/.bashrc && \
    echo "export CXX=mpicxx" >> ~jedi/.bashrc && \
    echo "export PYTHONPATH=/usr/local/lib:$PYTHONPATH" >> ~jedi/.bashrc && \
    echo "ulimit -s unlimited" >> ~jedi/.bashrc && \
    echo "ulimit -v unlimited" >> ~jedi/.bashrc && \
    echo "[credential]\n    helper = cache --timeout=7200" >> ~jedi/.gitconfig && \
    mkdir ~jedi/.openmpi && \
    echo "rmaps_base_oversubscribe = 1" >> ~jedi/.openmpi/mca-params.conf && \
    chown -R jedi:jedi ~jedi/.gitconfig ~jedi/.openmpi

CMD ["/bin/bash" , "-l"]
