set (deps_ZLIB     CACHE STRING "" FORCE)
set (deps_SZIP     CACHE STRING "" FORCE)
set (deps_LAPACK   CACHE STRING "" FORCE)
set (deps_JPEG     CACHE STRING "" FORCE)
set (deps_Jasper JPEG CACHE STRING "" FORCE)
set (deps_Freetype ZLIB CACHE STRING "" FORCE)
set (deps_XercesC  CACHE STRING "" FORCE)
set (deps_UDUNITS2 CACHE STRING "" FORCE)
set (deps_HDF5  ZLIB SZIP CACHE STRING "" FORCE)
